import Audio from "#/models/audio";
import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import cron from "node-cron";

// The five fields in the cron syntax represent
// (in order) minutes, hours, day of month, month, day of week

// cron.schedule("*/2 * * * * *", async () => {
//   console.log("running a task every day at 00:00");
// });

const generatedPlaylist = async () => {
  const result = await Audio.aggregate([
    { $sort: { likes: -1 } },
    { $group: { _id: "$category", audios: { $push: "$$ROOT._id" } } },
    { $sample: { size: 20 } },
  ]);

  result.map(async (item) => {
    await AutoGeneratedPlaylist.updateOne(
      { title: item._id },
      { $set: { items: item.audios } },
      { upsert: true }
    );
  });
};

cron.schedule("0 0 * * *", async () => {
  // this will run on every 24 hrs
  await generatedPlaylist();
});
