import { Router } from "express";
import {
  getAutoGeneratedPlaylist,
  getFollowersProfile,
  getFollowingsProfile,
  getFollowerProfilePublic,
  getIsFollowing,
  getPlaylistAudios,
  getPrivatePlaylistAudios,
  getPublicPlaylist,
  getPublicProfile,
  getPublicUploads,
  getRecommendByProfile,
  getUploads,
  updateFollower,
} from "@/controllers/profile";
import { isAuth, requireAuth } from "@/middleware/auth";

const router = Router();

router.get("/uploads", requireAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);
router.get("/recommended", isAuth, getRecommendByProfile);
router.get("/auto-generated-playlist", requireAuth, getAutoGeneratedPlaylist);
router.get("/followers", requireAuth, getFollowersProfile);
router.get("/followers/:profileId", requireAuth, getFollowerProfilePublic);
router.get("/followings", requireAuth, getFollowingsProfile);
router.get("/playlist-audios/:playlistId", getPlaylistAudios);
router.get("/is-following/:playlistId", requireAuth, getIsFollowing);
router.get(
  "/private-playlist-audios/:playlistId",
  requireAuth,
  getPrivatePlaylistAudios
);
router.post("/update-follower/:profileId", requireAuth, updateFollower);

export default router;
