import {
  getAutoGeneratedPlaylist,
  getFollowersProfile,
  getFollowingsProfile,
  getFollowerProfilePublic,
  getIsFollowing,
  getPlaylistAudios,
  getPrivatePlaylistAudios,
  getPublicPlaylist,
  getPublicProfile,
  getPublicUploads,
  getRecommendByProfile,
  getUploads,
  updateFollower,
} from "#/controllers/profile";
import { isAuth, mustAuth } from "#/middleware/auth";
import { Router } from "express";

const router = Router();

router.get("/uploads", mustAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);
router.get("/recommended", isAuth, getRecommendByProfile);
router.get("/auto-generated-playlist", mustAuth, getAutoGeneratedPlaylist);
router.get("/followers", mustAuth, getFollowersProfile);
router.get("/followers/:profileId", mustAuth, getFollowerProfilePublic);
router.get("/followings", mustAuth, getFollowingsProfile);
router.get("/playlist-audios/:playlistId", getPlaylistAudios);
router.get("/is-following/:playlistId", mustAuth, getIsFollowing);
router.get(
  "/private-playlist-audios/:playlistId",
  mustAuth,
  getPrivatePlaylistAudios
);
router.post("/update-follower/:profileId", mustAuth, updateFollower);

export default router;
